all:
	make -C clock
	make -C coordinates
	make -C deform
	make -C depth
	make -C objcontrol
	make -C screensaver
	make -C transform

clean:
	make -C clock clean
	make -C coordinates clean
	make -C deform clean
	make -C depth clean
	make -C objcontrol clean
	make -C screensaver clean
	make -C transform clean

install:
	make -C clock install
	make -C coordinates install
	make -C deform install
	make -C depth install
	make -C objcontrol install
	make -C screensaver install
	make -C transform install
